# Generated by Django 4.2.1 on 2023-05-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField()),
                ('is_paid', models.BooleanField()),
                ('purchase_status', models.CharField(choices=[('WP', 'Waiting Payment'), ('WR', 'Waiting for Robot'), ('C', 'Completed')], default='Waiting Payment', max_length=40)),
                ('client_name', models.CharField()),
                ('pharmacist', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pharmacist', verbose_name='Pharmacist')),
            ],
        ),
    ]
