# Generated by Django 4.2.1 on 2023-05-29 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='client_name',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pharmacist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pharmacist', verbose_name='Pharmacist'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='prescription',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_status',
            field=models.CharField(choices=[('WP', 'Waiting Payment'), ('WR', 'Waiting for Robot'), ('C', 'Completed')], default='Waiting Payment', max_length=40),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
