# Generated by Django 4.2.1 on 2023-05-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_purchase_client_name_purchase_pharmacist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='pharmacist',
        ),
    ]
