# Generated by Django 4.2.1 on 2023-05-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pharmacist_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='tutorial_category',
            new_name='pharmacist',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='client_name',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='prescription',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_status',
            field=models.CharField(choices=[('WP', 'Waiting Payment'), ('WR', 'Waiting for Robot'), ('C', 'Completed')], default='Waiting Payment', max_length=40),
        ),
    ]
