# Generated by Django 4.2.1 on 2023-05-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_purchase_pharmacist'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='pharmacist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pharmacist', verbose_name='Pharmacist'),
        ),
    ]
